org.gradle.jvmargs = -Xmx3G
org.gradle.java.home = C:/Users/Odin/.gradle/jdks/azul_systems__inc_-17-amd64-windows.2

# Mod Information
mod_version = 0.1.0
maven_group = com.cleanroommc.retrosophisticatedbackpacks
mod_id = retro_sophisticated_backpacks
archives_base_name = SophisticatedBackpacks-GTNH

# Kotlin — keep in sync with the Forgelin version used
kotlin_version = 2.1.10

# Build Options
use_mixins = false
use_coremod = true
use_assetmover = false
use_access_transformer = false

include_mod = true
coremod_plugin_class_name = com.cleanroommc.retrosophisticatedbackpacks.preloader.RSBPlugin
